USE [master]
GO

CREATE DATABASE [pedal]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
EXEC [pedal].[dbo].[sp_fulltext_database] @action = 'enable'
END
GO

ALTER DATABASE [pedal] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [pedal] SET ANSI_NULLS OFF
GO

ALTER DATABASE [pedal] SET ANSI_PADDING OFF
GO

ALTER DATABASE [pedal] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [pedal] SET ARITHABORT OFF
GO

ALTER DATABASE [pedal] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [pedal] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [pedal] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [pedal] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [pedal] SET CURSOR_DEFAULT GLOBAL
GO

ALTER DATABASE [pedal] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [pedal] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [pedal] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [pedal] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [pedal] SET DISABLE_BROKER
GO

ALTER DATABASE [pedal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [pedal] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [pedal] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [pedal] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [pedal] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [pedal] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [pedal] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [pedal] SET RECOVERY FULL
GO

ALTER DATABASE [pedal] SET MULTI_USER
GO

ALTER DATABASE [pedal] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [pedal] SET DB_CHAINING OFF
GO

ALTER DATABASE [pedal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [pedal] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [pedal] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [pedal] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

ALTER DATABASE [pedal] SET QUERY_STORE = ON
GO

ALTER DATABASE [pedal] SET QUERY_STORE (
    OPERATION_MODE = READ_WRITE,
    CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30),
    DATA_FLUSH_INTERVAL_SECONDS = 900,
    INTERVAL_LENGTH_MINUTES = 60,
    MAX_STORAGE_SIZE_MB = 1000,
    QUERY_CAPTURE_MODE = AUTO,
    SIZE_BASED_CLEANUP_MODE = AUTO,
    MAX_PLANS_PER_QUERY = 200,
    WAIT_STATS_CAPTURE_MODE = ON
)
GO

ALTER DATABASE [pedal] SET READ_WRITE
GO
